---
- name: znc-restart-monit
  service: name=monit state=restarted
  become: yes

- name: restart rinetd
  service: name=rinetd state=restarted
  become: yes

- name: znc-hup-instances
  shell: for f in {{znc_config_dir}}/*/znc.pid; do /bin/kill -HUP `cat $f`; done
  ignore_errors: yes
  become: yes
  become_user: "{{znc_system_user}}"
